apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-10T16:37:55Z"
  name: carts-canary
  resourceVersion: "38719"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: 7e9a5775-62ed-11ea-8a3a-42010a80021c
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
